# Configurazione per Render.com
services:
  # Backend Flask API
  - type: web
    name: litinvestorblog-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: '3.11'
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: litinvestorblog-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        value: Rio Capital Blog
      - key: CONTACT_ADMIN_EMAIL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: EMAIL_TEST_MODE
        value: false

  # Frontend React (Static Site)
  - type: web
    name: litinvestorblog-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_FMP_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database PostgreSQL
databases:
  - name: litinvestorblog-db
    databaseName: litinvestorblog
    user: litinvestorblog
    plan: free