"""add indexes

Revision ID: c4c6843b76f2
Revises: 211da0bff62f
Create Date: 2025-10-17 16:27:44.533850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c6843b76f2'
down_revision = '211da0bff62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index('idx_category_published', ['category_id', 'published'], unique=False)
        batch_op.create_index('idx_published_created', ['published', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_slug'))
        batch_op.drop_index(batch_op.f('ix_article_published'))
        batch_op.drop_index(batch_op.f('ix_article_created_at'))
        batch_op.drop_index(batch_op.f('ix_article_category_id'))
        batch_op.drop_index(batch_op.f('ix_article_author_id'))
        batch_op.drop_index('idx_published_created')
        batch_op.drop_index('idx_category_published')

    # ### end Alembic commands ###
